version: '3.8'

services:
  web:
    image: hbnb:latest
    build: .
    container_name: hbnb_web
    environment:
    - PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - hbnb_data:/app/data
    networks:
      - hbnb_network

networks:
  hbnb_network:
    driver: bridge

volumes:
  hbnb_data: